application: phppocket
version: 1
runtime: php55
api_version: 1

handlers:
- url: /busca
  script: busca.php
- url: /results
  script: results.php
- url: /results-todos
  script: results-todos.php
- url: /cadastro
  script: cadastro.php
- url: /cadastrando
  script: cadastrando.php
- url: /.*
  script: index.php