application: phppocket
version: 1
runtime: php55
api_version: 1

handlers:
- url: /busca
  script: busca.php
- url: /results
  script: tecnicos.php
- url: /tecnico
  script: tecnico.php
- url: /alterando
  script: alterando.php
- url: /connection
  script: connection.php
- url: /cadastro
  script: cadastro.php
- url: /cadastrando
  script: cadastrando.php
- url: /results_usuario
  script: results_usuario.php
- url: /.*
  script: index.php